Repository Infomaniak/ios-kDrive, pull requests merged in 2021-07, with the labels that each got.

#172 Fix collection register
  kDrive/UI/Controller/Files/FileListViewController.swift
  kDrive/UI/Controller/Files/Save File/SaveFileViewController.swift
  kDrive/UI/Controller/Photo/SavePhotoViewController.swift
  kDrive/UI/Controller/Scan/SaveScanViewController.swift
  kDrive/UI/View/Home/RecentActivityTableViewCell.swift
  kDrive/UI/View/NewFolder/NewFolderLocationTableViewCell.swift
  kDrive/UI/View/NewFolder/NewFolderShareRuleTableViewCell.swift
Labels: bug

#175 Fix download multiple files
  kDrive/UI/Controller/Files/SelectFloatingPanelTableViewController.swift
Labels: bug

#189 natural date added to file
  kDrive/Resources/de.lproj/Localizable.strings
  kDrive/Resources/en.lproj/Localizable.strings
  kDrive/Resources/es.lproj/Localizable.strings
  kDrive/Resources/fr.lproj/Localizable.strings
  kDrive/Resources/it.lproj/Localizable.strings
  kDrive/UI/View/Files/FileCollectionViewCell.swift
  kDrive/UI/View/Files/FloatingPanel/FloatingPanelTitleTableViewCell.swift
  kDriveCore/Utils/Constants.swift
Labels: enhancement, optimization, user feedback

#180 Add confirmation modal and improve photo deletion
  kDrive/AppDelegate.swift
  kDriveCore/Data/UploadQueue/PhotoLibraryUploader.swift
Labels: enhancement, optimization

#108 Improve upload queue
  kDrive/UI/Controller/Files/FileListViewController.swift
  kDrive/UI/Controller/Files/Upload/UploadQueueViewController.swift
  kDrive/UI/View/Files/Upload/UploadTableViewCell.swift
  kDriveCore/Data/Cache/AccountManager.swift
  kDriveCore/Data/Cache/BackgroundRealm.swift
  kDriveCore/Data/Cache/DriveInfosManager.swift
  kDriveCore/Data/UploadQueue/UploadOperation.swift
  kDriveCore/Data/UploadQueue/UploadQueue.swift
  kDriveCore/Utils/Throttler.swift
Labels: bug

#197 Reduce Realm usage to improve uploads stability
  kDrive/UI/Controller/Files/FileListViewController.swift
  kDriveCore/Data/UploadQueue/UploadOperation.swift
Labels: bug

#204 fixed file relativeTime
  kDriveCore/Utils/Constants.swift
Labels: bug

#205 fix fileQuickAction download
  kDrive/UI/View/Files/FloatingPanel/FloatingPanelCollectionViewCell.swift
  kDrive/UI/View/Files/FloatingPanel/FloatingPanelTableViewCell.swift
Labels: bug

#209 recentActivity fixed
  kDrive/UI/View/Home/RecentActivityTableViewCell.swift
Labels: bug

#145 Update offline files improvements
  kDrive/AppDelegate.swift
  kDrive/UI/Controller/Files/FileQuickActionsFloatingPanelViewController.swift
  kDrive/UI/Controller/Files/SelectFloatingPanelTableViewController.swift
  kDriveCore/Data/Api/ApiRoutes.swift
  kDriveCore/Data/Api/DriveApiFetcher.swift
  kDriveCore/Data/Cache/DriveFileManager.swift
  kDriveCore/Data/Models/FileActivity.swift
  kDriveCore/Utils/DriveUserDefaults+Extension.swift
Labels: enhancement, optimization, user feedback

#211 Improve snackbar with UIWindow
  kDrive/UI/Controller/Files/FileDetailViewController.swift
  kDrive/UI/Controller/Files/FileQuickActionsFloatingPanelViewController.swift
  kDrive/UI/Controller/Menu/Trash/TrashViewController.swift
  kDrive/Utils/UIConstants.swift
  kDriveCore/Utils/IKSnackBar.swift
Labels: enhancement, optimization

#216 Fix IB warnings
  kDrive/AppDelegate.swift
  kDrive/UI/Controller/Base.lproj/Main.storyboard
  kDrive/UI/Controller/Floating Panel Information/AccessFileFloatingPanelViewController.swift
  kDrive/UI/Controller/Floating Panel Information/DriveMaintenanceFloatingPanelViewController.swift
  kDrive/UI/Controller/Floating Panel Information/DropBoxFloatingPanelViewController.swift
  kDrive/UI/Controller/Floating Panel Information/InformationFloatingPanel.storyboard
  kDrive/UI/Controller/Floating Panel Information/InformationFloatingPanelViewController.swift
  kDrive/UI/Controller/Floating Panel Information/MigratePhotoSyncSettingsFloatingPanelViewController.swift
  kDrive/UI/Controller/Floating Panel Information/NoAccessFloatingPanelViewController.swift
  kDrive/UI/Controller/Floating Panel Information/SavePhotosFloatingPanelViewController.swift
  kDrive/UI/Controller/Floating Panel Information/SecureLinkFloatingPanelViewController.swift
  kDrive/UI/Controller/Floating Panel Information/ShareFloatingPanelViewController.swift
  kDrive/UI/Controller/Floating Panel Information/UnsupportedExtensionFloatingPanelViewController.swift
  kDrive/UI/Controller/Floating Panel Information/UpdateFloatingPanelViewController.swift
  kDrive/UI/View/Home/RecentActivityCollectionViewCell.xib
Labels: bug

#218 New dropbox activity types
  kDrive/UI/Controller/Files/DropBox/ManageDropBoxViewController.swift
  kDrive/UI/View/Files/FileDetail/FileDetailActivityTableViewCell.swift
  kDriveCore/Data/Cache/DriveFileManager.swift
  kDriveCore/Data/Models/FileActivity.swift
Labels: enhancement, optimization

#231 Fix crashes
  kDrive/UI/Controller/Files/Preview/PreviewViewController.swift
  kDrive/UI/Controller/Home/HomeTableViewController.swift
Labels: bug
