Repository Infomaniak/ios-kDrive, pull requests merged in 2021-06, with the labels that each got.

#153 Image preview zoom
  kDrive/UI/Controller/Files/Preview/PreviewViewController.swift
  kDrive/UI/View/Files/Preview/DownloadingPreviewCollectionViewCell.swift
  kDrive/UI/View/Files/Preview/ImagePreviewCollectionViewCell.swift
  kDrive/UI/View/Files/Preview/ImagePreviewCollectionViewCell.xib
Labels: enhancement

#107 Add sort options to photo list
  kDrive/Resources/Assets.xcassets/filter.imageset/Contents.json
  kDrive/Resources/Assets.xcassets/filter.imageset/filter.svg
  kDrive/UI/Controller/Menu/FloatingPanelPhotoSortViewController.swift
  kDrive/UI/Controller/Menu/Menu.storyboard
  kDrive/UI/Controller/Menu/PhotoListViewController.swift
  kDriveCore/Data/Models/PhotoSortMode.swift
  kDriveCore/Utils/DriveUserDefaults+Extension.swift
Labels: enhancement, optimization, user feedback

#169 Refactor file import workflow
  kDrive/AppDelegate.swift
  kDrive/Resources/de.lproj/Localizable.strings
  kDrive/Resources/en.lproj/Localizable.strings
  kDrive/Resources/es.lproj/Localizable.strings
  kDrive/Resources/fr.lproj/Localizable.strings
  kDrive/Resources/it.lproj/Localizable.strings
  kDrive/UI/Controller/Create File/PlusButtonFloatingPanelViewController.swift
  kDrive/UI/Controller/Files/FileListViewController.swift
  kDrive/UI/Controller/Files/FileQuickActionsFloatingPanelViewController.swift
  kDrive/UI/Controller/Files/Save File/SaveFileViewController.swift
  kDrive/UI/Controller/Photo/PhotoPickerDelegate.swift
  kDrive/UI/Controller/Photo/SavePhotoViewController.swift
  kDrive/UI/Controller/Scan/SaveScanViewController.swift
  kDrive/UI/Controller/Scan/ScanNavigationViewController.swift
  kDrive/UI/View/Files/SaveFile/ScanTypeTableViewCell.swift
  kDrive/Utils/UIConstants.swift
  kDriveCore/Utils/FileImportHelper.swift
  kDriveCore/Utils/IKSnackBar.swift
  kDriveCore/Utils/NotificationsHelper.swift
Labels: enhancement, optimization
