Repository Infomaniak/ios-kDrive, pull requests merged in 2021-12, with the labels that each got.

#425 Calculate list changes in background
  kDrive/UI/Controller/Files/FileListViewController.swift
Labels: optimization

#432 Use embedded objects in drive infos
  kDriveCore/Data/Cache/DriveFileManager.swift
  kDriveCore/Data/Cache/DriveInfosManager.swift
  kDriveCore/Data/Models/Category.swift
  kDriveCore/Data/Models/CategoryRights.swift
  kDriveCore/Data/Models/Drive.swift
  kDriveCore/Data/Models/Team.swift
Labels: optimization

#441 Fix file cell category badges reuse
  kDrive/UI/View/Files/FileCollectionViewCell.swift
  kDrive/UI/View/Files/FileCollectionViewCell.xib
Labels: bug

#443 Fix activities add & categories
  kDriveCore/Data/Api/ApiRoutes.swift
  kDriveCore/Data/Cache/DriveFileManager.swift
Labels: bug

#442 Upload queue observer on main queue
  kDrive/UI/Controller/Files/Upload/UploadQueueFoldersViewController.swift
  kDrive/UI/Controller/Files/Upload/UploadQueueViewController.swift
Labels: bug

#439 Convert category floating panel to collection view
  kDrive/UI/Controller/Files/Categories/ManageCategoriesViewController.swift
  kDrive/UI/Controller/Files/Categories/ManageCategoryFloatingPanelViewController.swift
  kDrive/UI/Controller/Files/FileActionsFloatingPanelViewController.swift
  kDrive/UI/View/Files/Categories/CategoryFloatingPanelCollectionTableViewCell.swift
  kDrive/UI/View/Files/Categories/CategoryFloatingPanelCollectionTableViewCell.xib
  kDrive/UI/View/Files/FloatingPanel/FloatingPanelQuickActionCollectionViewCell.swift
Labels: enhancement

#447 add offline checkmark and download progress
  kDrive/UI/View/Files/FileGridCollectionViewCell.xib
Labels: bug

#449 Add unit test for category workflow
  kDriveTests/DriveApiTests.swift
Labels: optimization

#448 Use `updateFileProperty` method where it makes sense
  kDrive/UI/Controller/Files/FileActionsFloatingPanelViewController.swift
  kDrive/UI/Controller/Files/FileDetailViewController.swift
  kDrive/UI/Controller/Files/Rights and Share/ShareAndRightsViewController.swift
  kDriveCore/Data/Cache/DriveFileManager.swift
Labels: optimization

#452 Improve CI
  .github/workflows/ci.yml
Labels: optimization

#456 Upgrade dependencies (Bug fix for -> Core 1.1.3 | FloatingPanel 2.5.1)
  .package.resolved
Labels: bug, enhancement

#461 Fix unowned reference in audio preview cell
  kDrive/UI/View/Files/Preview/AudioCollectionViewCell.swift
Labels: bug

#459 Fix save file in file actions panel
  kDrive/UI/Controller/Files/FileActionsFloatingPanelViewController.swift
  kDrive/UI/Controller/Files/SelectFloatingPanelTableViewController.swift
Labels: bug

#458 Fix search filters header size
  kDrive/UI/Controller/Files/Search/Search.storyboard
  kDrive/UI/Controller/Files/Search/SearchFiltersViewController.swift
Labels: bug

#462 Fix network observation (Sentry - KDRIVE-IOS-YJ)
  kDrive/AppDelegate.swift
Labels: bug

#465 Improve search filters
  kDrive/UI/Controller/Files/FileListViewController.swift
  kDrive/UI/Controller/Files/Search/Filters.swift
Labels: bug, optimization

#480 Fix home
  kDrive/UI/Controller/Home/HomeRecentActivitiesController.swift
  kDrive/UI/Controller/Home/HomeRecentFilesController.swift
  kDrive/UI/Controller/Home/HomeViewController.swift
  kDrive/UI/View/Home/FileHomeCollectionViewCell.swift
Labels: bug
