Repository Infomaniak/ios-kDrive, pull requests merged in 2022-01, with the labels that each got.

#487 Fix toggle multiple selection & trash load
  kDrive/UI/Controller/Files/FileListViewController.swift
  kDrive/UI/Controller/Menu/Trash/TrashViewController.swift
Labels: bug

#490 Attempt fix activity cell
  kDrive/UI/View/Home/RecentActivityCollectionViewCell.swift
Labels: bug

#497 Refactor realm opening logging
  kDriveCore/Data/Cache/BackgroundRealm.swift
  kDriveCore/Data/Cache/DriveFileManager.swift
  kDriveCore/Data/Cache/DriveInfosManager.swift
  kDriveCore/Data/UploadQueue/UploadQueue.swift
  kDriveCore/Utils/Logging.swift
Labels: optimization

#495 Fix search view refresh control
  kDrive/UI/Controller/Files/Search/SearchViewController.swift
Labels: bug

#498 Fix favorite activity
  kDriveCore/Data/Cache/DriveFileManager.swift
Labels: bug

#502 Remove useless CGFloat casting
  kDrive/UI/Controller/Files/ColorSelectionFloatingPanelViewController.swift
  kDrive/UI/Controller/Files/FileDetailViewController.swift
  kDrive/UI/Controller/Files/FileListViewController.swift
  kDrive/UI/Controller/Files/Preview/PreviewViewController.swift
  kDrive/UI/Controller/Files/Upload/UploadQueueViewController.swift
  kDrive/UI/View/Files/FileCollectionViewCell.swift
  kDrive/UI/View/Files/FloatingPanel/FloatingPanelActionCollectionViewCell.swift
  kDrive/UI/View/Files/FloatingPanel/FloatingPanelQuickActionCollectionViewCell.swift
  kDrive/UI/View/Home/RecentActivityCollectionViewCell.swift
  kDrive/UI/View/Menu/MainTabBar.swift
  kDrive/UI/View/NewFolder/NewFolderShareRuleUserLayout.swift
  kDrive/Utils/UIScrollView+Extension.swift
  kDriveCore/UI/Alert/AlertChoiceViewController.swift
  kDriveCore/UI/MaterialOutlinedTextField+Extension.swift
  kDriveCore/UI/UIConstants.swift
  kDriveCore/Utils/FileImportHelper.swift
  kDriveCore/Utils/IKSegmentedControl.swift
Labels: optimization

#514 Prepare for API v2
  .package.resolved
  kDrive/UI/Controller/Files/ColorSelectionFloatingPanelViewController.swift
  kDrive/UI/Controller/Files/Search/DateRangePickerViewController.swift
  kDriveCore/Data/Api/ApiRoutes.swift
  kDriveCore/Data/Api/DriveApiFetcher.swift
  kDriveCore/Data/Api/Endpoint.swift
  kDriveCore/Data/Cache/DriveFileManager.swift
  kDriveCore/Data/Models/DriveError.swift
  kDriveCore/Data/Models/File.swift
  kDriveCore/Data/Models/UploadFile.swift
  kDriveTests/DriveApiTests.swift
Labels: enhancement

#519 Small improvement of DriveApiFetcher v2
  kDriveCore/Data/Api/DriveApiFetcher.swift
  kDriveCore/Data/Api/Endpoint.swift
  kDriveCore/Utils/ParameterEncoder+Extension.swift
Labels: enhancement, api-v2

#560 Create URLConstants struct
  kDrive/Data/App Version/AppVersion.swift
  kDrive/IAP/StoreRequest.swift
  kDrive/UI/Controller/DriveErrorViewController.swift
  kDrive/UI/Controller/LaunchPanelsController.swift
  kDrive/UI/Controller/Menu/AboutTableViewController.swift
  kDrive/UI/Controller/Menu/MenuViewController.swift
  kDrive/UI/Controller/Menu/StoreViewController.swift
  kDrive/UI/Controller/RegisterViewController.swift
  kDriveCore/Data/Api/ApiRoutes.swift
  kDriveCore/Data/Api/Endpoint.swift
  kDriveCore/Utils/Constants.swift
Labels: optimization

#569 fix bug refresh action floating panel
  kDrive/UI/Controller/Files/FileActionsFloatingPanelViewController.swift
Labels: bug
