Repository Infomaniak/ios-kDrive, pull requests merged in 2022-02, with the labels that each got.

#565 Save file icon preview
  kDrive/UI/Controller/Files/Save File/SaveFileViewController.swift
  kDrive/UI/View/Files/Upload/UploadCardView.swift
  kDrive/UI/View/Files/Upload/UploadTableViewCell.swift
  kDrive/UI/View/Files/Upload/UploadTableViewCell.xib
  kDriveCore/Data/Models/UploadFile.swift
  kDriveCore/Utils/FileImportHelper.swift
  kDriveCore/Utils/FilePreviewHelper.swift
Labels: enhancement

#592 Fix reload drive after account change
  kDrive/UI/Controller/Files/FileListViewController.swift
Labels: bug

#595 Update search after API v2 change
  Tuist/ProjectDescriptionHelpers/Constants.swift
  Tuist/ProjectDescriptionHelpers/ExtensionTarget.swift
  Tuist/ProjectDescriptionHelpers/SettingsDictionary+Extension.swift
  kDrive/UI/View/Files/Upload/UploadTableViewCell.swift
  kDriveCore/Data/Api/Endpoint.swift
  kDriveCore/Data/Cache/DriveFileManager.swift
  kDriveCore/Data/Models/File.swift
Labels: api-v2

#596 Display error for url preview when scheme is not http/s
  kDrive/UI/Controller/Files/FilePresenter.swift
  kDrive/UI/Controller/Files/Preview/PreviewViewController.swift
Labels: bug

#597 Use API v2 for file activities
  kDrive/AppDelegate.swift
  kDrive/UI/Controller/Files/FileDetailViewController.swift
  kDrive/UI/Controller/Files/FileListViewController.swift
  kDrive/UI/Controller/Home/HomeRecentActivitiesController.swift
  kDrive/UI/View/Files/FileDetail/FileDetailActivityTableViewCell.swift
  kDrive/UI/View/Files/FileDetail/FileDetailCommentTableViewCell.swift
  kDrive/UI/View/Home/RecentActivityBottomTableViewCell.swift
  kDrive/UI/View/Home/RecentActivityCollectionViewCell.swift
  kDriveCore/Data/Api/ApiRoutes.swift
  kDriveCore/Data/Api/DriveApiFetcher.swift
  kDriveCore/Data/Api/Endpoint.swift
  kDriveCore/Data/Cache/DriveFileManager.swift
  kDriveCore/Data/Models/ApiResponse.swift
  kDriveCore/Data/Models/Comment.swift
  kDriveCore/Data/Models/FileActivity.swift
  kDriveCore/Utils/Constants.swift
  kDriveFileProvider/FileProviderEnumerator.swift
  kDriveTests/DriveApiTests.swift
Labels: api-v2

#602 Fix preview title
  kDrive/UI/Controller/Files/Preview/PreviewViewController.swift
Labels: bug

#608 Fix shared with me option in menu
  kDrive/UI/Controller/Menu/MenuViewController.swift
Labels: bug

#611 Fix "No Preview" cell
  kDrive/UI/Controller/Files/FileActionsFloatingPanelViewController.swift
  kDrive/UI/Controller/Files/FilePresenter.swift
  kDrive/UI/View/Files/Preview/NoPreviewCollectionViewCell.swift
  kDrive/UI/View/Files/Preview/NoPreviewCollectionViewCell.xib
  kDriveCore/Data/Models/File.swift
Labels: bug

#613 Fix file icon tint color in home recent activities
  kDrive/UI/View/Home/RecentActivityBottomTableViewCell.swift
  kDrive/UI/View/Home/RecentActivityPreviewCollectionViewCell.swift
Labels: bug

#627 Fix race condition in Account Manager
  kDriveCore/Data/Cache/AccountManager.swift
Labels: bug

#626 Fix FP domain path with identical drives
  kDriveCore/Data/Cache/DriveInfosManager.swift
  kDriveCore/Utils/DriveUserDefaults+Extension.swift
Labels: bug
