Repository Infomaniak/ios-kDrive, pull requests merged in 2025-08, with the labels that each got.

#1630 fix(FileCollectionViewCell): Disable separator in simple list style
  kDrive/UI/View/Files/FileCollectionViewCell.swift
Labels: bug

#1628 fix: Realm crash invalidation
  kDrive/UI/Controller/Files/Preview/PreviewViewController.swift
Labels: bug

#1634 ci: Split tests from the rest of the ci checks
  .github/workflows/ci.yml
Labels: CI

#1643 fix: Modify deeplinks regex to handle all cases
  kDriveCore/Utils/Deeplinks/SharedWithMeLink.swift
  kDriveCore/Utils/Deeplinks/TrashLink.swift
Labels: deeplink

#1642 fix: Duplicate bulk action
  kDrive/AppRouter+SharedWithMe.swift
  kDrive/AppRouter+Trash.swift
  kDrive/AppRouter.swift
  kDrive/UI/Controller/Files/MultipleSelectionFloatingPanelViewController.swift
  kDriveCore/Utils/AppNavigable.swift
  kDriveCore/Utils/InExtensionRouter.swift
  kDriveTestShared/MCKRouter.swift
Labels: bug

#1645 refactor: New method to open directoryLink
  kDrive/AppRouter.swift
  kDriveCore/Data/Cache/AccountManager.swift
  kDriveCore/Utils/DeeplinkParser.swift
  kDriveCore/Utils/Deeplinks/DeeplinkService.swift
  kDriveCore/Utils/Deeplinks/DirectoryLink.swift
  kDriveCore/Utils/Deeplinks/UniversalLinksHelper.swift
  kDriveCore/Utils/Routable.swift
  kDriveTests/kDriveCore/DeepLinks/UTDirectoryLink.swift
  kDriveTests/kDriveCore/DeepLinks/UTPrivateShareLink.swift
  kDriveTests/kDriveCore/DeepLinks/UTTrashLink.swift
Labels: deeplink

#1647 fix: Add available offline is always enabled in multi selection
  kDrive/UI/Controller/Files/MultipleSelectionFloatingPanelViewController.swift
Labels: bug

#1646 refactor: New method to open filePreview
  kDrive/AppRouter.swift
  kDriveCore/Data/Cache/AccountManager.swift
  kDriveCore/Utils/DeeplinkParser.swift
  kDriveCore/Utils/Deeplinks/DeeplinkService.swift
  kDriveCore/Utils/Deeplinks/FilePreviewLink.swift
  kDriveCore/Utils/Deeplinks/UniversalLinksHelper.swift
  kDriveCore/Utils/Routable.swift
  kDriveTests/kDriveCore/DeepLinks/UTFilePreviewLink.swift
Labels: deeplink

#1648 fix: Remove some warnings
  kDrive/AppDelegate.swift
  kDrive/AppRestorationService.swift
  kDrive/SceneDelegate.swift
  kDrive/UI/Controller/Files/FileActionsFloatingPanelViewController.swift
  kDrive/UI/Controller/Files/Save File/SaveFileViewController+FooterButtonDelegate.swift
  kDrive/UI/Controller/Home/HomeLargeTitleHeaderView.swift
  kDrive/UI/Controller/Scan/SaveScanViewController.swift
  kDrive/UI/View/Files/Upload/RPCircularProgress.swift
  kDriveCore/Data/Cache/AccountManager.swift
  kDriveCore/Data/Cache/DriveFileManager/DriveFileManager.swift
  kDriveCore/Data/DownloadQueue/DownloadQueueable.swift
  kDriveCore/Utils/AppNavigable.swift
  kDriveCore/Utils/DriveUserDefaults+Extension.swift
Labels: bug

#1651 chore: Release build 5.8.2-b47
  TestFlight/WhatToTest.en-GB.txt
  TestFlight/WhatToTest.fr-FR.txt
  Tuist/Package.resolved
  Tuist/ProjectDescriptionHelpers/Constants.swift
Labels: release

#1649 refactor: Replace UniversalLinksHelper with AppRouter+PublicShare
  kDrive/AppRouter+PublicShare.swift
  kDrive/AppRouter.swift
  kDrive/Utils/FileActionsHelper.swift
  kDriveCore/Data/Models/File.swift
  kDriveCore/Utils/DeeplinkParser.swift
  kDriveCore/Utils/Deeplinks/DeeplinkService.swift
  kDriveCore/Utils/Deeplinks/PublicShareLink.swift
  kDriveCore/Utils/Routable.swift
  kDriveTests/kDriveCore/DeepLinks/UTPublicShareLink.swift
Labels: deeplink

#1658 feat: Handle navigation to basic deeplinks
  kDrive/AppRouter+BasicLink.swift
  kDrive/AppRouter+SharedWithMe.swift
  kDrive/AppRouter+Trash.swift
  kDrive/AppRouter.swift
  kDrive/UI/Controller/Files/External/BaseInfoViewController.swift
  kDrive/UI/Controller/Menu/Share/PublicShareViewModel.swift
  kDrive/Utils/FileActionsHelper.swift
  kDriveCore/Data/Cache/AccountManager.swift
  kDriveCore/Utils/DeeplinkParser.swift
  kDriveCore/Utils/Deeplinks/BasicLink.swift
  kDriveCore/Utils/Deeplinks/DeeplinkService.swift
  kDriveCore/Utils/Routable.swift
  kDriveTests/kDriveCore/DeepLinks/UTBasicLink.swift
Labels: deeplink

#1663 refactor: Remove unused matomo categories
  kDriveCore/Utils/MatomoUtils+Extension.swift
Labels: matomo

#1670 fix: Allow multiselect download in the same folder
  kDrive/UI/Controller/Files/MultipleSelectionFloatingPanelViewController+Actions.swift
Labels: optimization

#1672 fix: Quick actions fix for iPad
  kDrive/SceneDelegate.swift
  kDrive/UI/Controller/Photo/PhotoPickerDelegate.swift
Labels: bug

#1673 chore: Release build 5.8.3-b50
  TestFlight/WhatToTest.en-GB.txt
  TestFlight/WhatToTest.fr-FR.txt
  Tuist/Package.resolved
Labels: release
