Repository Infomaniak/ios-kDrive, pull requests merged in 2025-06, with the labels that each got.

#1585 refactor: Use EmailCheck core and remove unused code
  kDrive/UI/View/Files/FileDetail/ShareLink/InviteUserTableViewCell.swift
  kDriveCore/Utils/Constants.swift
Labels: refactor

#1579 ci: Correctly cancel tasks
  .github/workflows/ci.yml
  .github/workflows/swiftformat.yml
  .github/workflows/swiftlint.yml
Labels: CI

#1543 fix: Delete photos in realm when we change drive for sync
  kDrive/AppRouter.swift
  kDrive/UI/Controller/Menu/PhotoSyncSettingsViewController.swift
  kDriveCore/Data/Upload/Servicies/PhotoLibraryUploader/PhotoLibraryCleanerService.swift
  kDriveCore/Data/Upload/Servicies/PhotoLibraryUploader/PhotoLibraryUploader+Scan.swift
  kDriveCore/Data/Upload/Servicies/PhotoLibraryUploader/PhotoLibraryUploader+Sync.swift
  kDriveCore/Data/Upload/Servicies/PhotoLibraryUploader/PhotoLibraryUploader.swift
  kDriveCore/Data/Upload/Servicies/UploadService/UploadService+Datasource.swift
  kDriveCore/Data/Upload/Servicies/UploadService/UploadService.swift
  kDriveCore/Data/Upload/UploadQueue/Queue/KeyedUploadOperationable.swift
  kDriveCore/Data/Upload/UploadQueue/Queue/PhotoUploadQueue.swift
  kDriveCore/Data/Upload/UploadQueue/Queue/UploadQueue+Queue.swift
  kDriveCore/Data/Upload/UploadQueue/Queue/UploadQueue.swift
  kDriveCore/Data/Upload/UploadQueue/Queue/UploadQueueable.swift
  kDriveCore/Services/BackgroundTasksService.swift
  kDriveTestShared/MCKPhotoLibraryScanable.swift
Labels: bug, enhancement

#1589 refactor: Remove and add strings
  kDrive/Resources/de.lproj/Localizable.strings
  kDrive/Resources/en.lproj/Localizable.strings
  kDrive/Resources/es.lproj/Localizable.strings
  kDrive/Resources/fr.lproj/Localizable.strings
  kDrive/Resources/it.lproj/Localizable.strings
  kDrive/UI/Controller/Files/Save File/SelectFolderViewController.swift
Labels: optimization

#1590 chore: Release build 5.7.0-b24
  TestFlight/WhatToTest.en-GB.txt
  TestFlight/WhatToTest.fr-FR.txt
  Tuist/Package.resolved
Labels: release

#1553 feat: Small file direct upload
  kDriveCore/Data/Upload/UploadQueue/Chunk/RangeProvider.swift
  kDriveCore/Data/Upload/UploadQueue/Operation/UploadOperation+Error.swift
  kDriveCore/Data/Upload/UploadQueue/Operation/UploadOperation+UploadSession.swift
  kDriveCore/Data/Upload/UploadQueue/Operation/UploadOperation.swift
  kDriveCore/Data/Upload/UploadQueue/Queue/UploadQueue+Queue.swift
  kDriveCore/Data/Upload/UploadQueue/Queue/UploadQueue.swift
Labels: enhancement, feature, Ecological design

#1595 chore: Release build 5.7.0-b25
  TestFlight/WhatToTest.en-GB.txt
  TestFlight/WhatToTest.fr-FR.txt
Labels: release

#1596 ci: Call tuist generate less often
  .github/workflows/ci.yml
  ci_scripts/ci_post_xcodebuild.sh
Labels: bug, CI
