Repository Infomaniak/ios-kDrive, pull requests merged in 2025-01, with the labels that each got.

#1357 fix: Realm crash invalidated file
  kDriveCore/Data/Models/Drive/Drive.swift
Labels: bug

#1381 fix(MultipleSelectionFloatingPanelViewController): Correct background color
  kDrive/UI/Controller/Files/MultipleSelectionFloatingPanelViewController.swift
Labels: bug

#1383 fix(PhotoSync): Skip iCloud asset on iCloud critical error
  kDriveCore/Data/UploadQueue/Servicies/PhotoLibraryUploader+Scan.swift
  kDriveCore/Utils/PHAsset/PHAssetIdentifier.swift
  kDriveCore/Utils/Sentry/SentryDebug+Upload.swift
Labels: bug

#1385 fix(PhotoSync): Do not start if not enough free space available
  kDrive/UI/Controller/Menu/PhotoSyncSettingsViewController.swift
  kDriveCore/Data/UploadQueue/Servicies/FreeSpace/FreeSpaceService.swift
Labels: bug

#1349 feat: Add to my drive action
  kDrive/AppRouter.swift
  kDrive/UI/Controller/Files/File List/FileListViewController.swift
  kDrive/UI/Controller/Files/File List/FileListViewModel.swift
  kDrive/UI/Controller/Files/FileActionsFloatingPanelViewController+Actions.swift
  kDrive/UI/Controller/Files/FileDetailViewController.swift
  kDrive/UI/Controller/Files/FilePresenter.swift
  kDrive/UI/Controller/Files/FloatingPanelAction.swift
  kDrive/UI/Controller/Files/PublicShareAction.swift
  kDrive/UI/Controller/Files/RootMenuViewController.swift
  kDrive/UI/Controller/Files/Save File/SaveFileViewController+FooterButtonDelegate.swift
  kDrive/UI/Controller/Files/Save File/SaveFileViewController+SelectFolderDelegate.swift
  kDrive/UI/Controller/Files/Save File/SaveFileViewController+UITableViewDataSource.swift
  kDrive/UI/Controller/Files/Save File/SaveFileViewController.swift
  kDrive/UI/Controller/Files/Save File/SelectFolderViewController.swift
  kDrive/UI/Controller/Home/HomeViewController.swift
  kDrive/UI/Controller/LoginDelegateHandler.swift
  kDrive/UI/Controller/Menu/Share/PublicShareViewModel.swift
  kDrive/UI/Controller/OnboardingViewController.swift
  kDrive/UI/View/Files/FileListBarButton.swift
  kDrive/UI/View/Upsale/NoDriveUpsaleViewController.swift
  kDrive/UI/View/Upsale/UpsaleViewController.swift
  kDriveCore/DI/FactoryService.swift
  kDriveCore/Data/Api/DriveApiFetcher.swift
  kDriveCore/Data/Api/Endpoint+Share.swift
  kDriveCore/Data/Api/Endpoint+Trash.swift
  kDriveCore/Data/Cache/AccountManager.swift
  kDriveCore/Data/DownloadQueue/DownloadQueue.swift
  kDriveCore/Utils/AppNavigable.swift
  kDriveCore/Utils/Deeplinks/DeeplinkService.swift
  kDriveCore/Utils/Deeplinks/PublicShareLink.swift
  kDriveCore/Utils/Deeplinks/UniversalLinksHelper.swift
  kDriveCore/Utils/MatomoUtils.swift
  kDriveCore/VideoPlayer/VideoPlayer.swift
  kDriveTestShared/MCKRouter.swift
  kDriveTests/kDrive/Launch/MockAccountManager.swift
Labels: public_share

#1376 feat: Public share Matomo
  kDrive/UI/Controller/Files/FileActionsFloatingPanelViewController+Actions.swift
  kDrive/UI/Controller/Files/PublicShareAction.swift
  kDrive/UI/Controller/Files/Save File/SaveFileViewController+FooterButtonDelegate.swift
  kDrive/UI/Controller/Files/Save File/SaveFileViewController.swift
  kDrive/UI/Controller/Menu/Share/PublicShareViewModel.swift
  kDrive/UI/View/Upsale/UpsaleViewController.swift
  kDriveCore/Utils/MatomoUtils.swift
Labels: public_share

#1378 fix: Public Share action sheet offset
  kDrive/UI/Controller/Create File/FloatingPanelLayouts.swift
Labels: public_share

#1392 feat: Public Share video streaming in previews
  kDriveCore/VideoPlayer/VideoPlayer.swift
Labels: public_share

#1379 fix: Public Share works with app lock
  kDrive/AppRouter.swift
  kDrive/UI/Controller/LoginDelegateHandler.swift
Labels: public_share

#1380 chore(AppDelegate): Clean Public Share sample links
  kDrive/AppDelegate.swift
Labels: public_share

#1388 refactor(UploadQueueViewController): Using DifferenceKit to prevent a crash
  kDrive/UI/Controller/Files/Upload/UploadQueueViewController.swift
  kDriveCore/Data/Models/Upload/CornerCellContainer.swift
  kDriveCore/Data/Models/Upload/UploadFile.swift
Labels: bug

#1395 feat(PreviewViewController): Download in cache public share files for preview
  kDrive/UI/Controller/Files/Preview/PreviewViewController.swift
  kDriveCore/Data/DownloadQueue/DownloadQueue.swift
Labels: public_share

#1389 refactor(UploadQueueFoldersViewController): Using DifferenceKit to fix a crash
  kDrive/UI/Controller/Files/Upload/UploadQueueFoldersViewController.swift
Labels: bug

#1396 fix(FileCollectionViewCell): Invalidated realm object in async code
  kDrive/UI/View/Files/FileCollectionViewCell.swift
Labels: bug

#1398 fix(PreviewViewController): Disable edit button in public share mode
  kDrive/UI/Controller/Files/Preview/PreviewViewController.swift
Labels: public_share

#1399 fix(PreviewViewController): Realm crash with an invalidated File
  kDrive/UI/Controller/Files/Preview/PreviewViewController.swift
Labels: bug

#1404 fix(deeplinkService): Prevent display post login of locked and expired views
  kDrive/UI/Controller/Files/External/BaseInfoViewController.swift
Labels: bug

#1403 fix(publicShare): Audio preview
  kDrive/UI/Controller/Files/Preview/PreviewViewController.swift
  kDriveCore/AudioPlayer/SingleTrackPlayer.swift
Labels: bug

#1406 fix(publicShare): Preview retry download office file as PDF woking in public share mode
  kDrive/UI/Controller/Files/OnlyOfficeViewController.swift
  kDriveCore/Data/Cache/PdfPreviewCache.swift
Labels: bug, public_share

#1391 fix: InExtensionRouter availlable in extension mode to prevent crashes
  kDrive/Utils/AppFactoryService.swift
  kDriveCore/Utils/InExtensionRouter.swift
Labels: bug

#1413 refactor: Public share metadata standalone file
  kDriveCore/Data/Api/DriveApiFetcher.swift
  kDriveCore/Data/Api/PublicShareMetadata.swift
Labels: public_share

#1412 fix: Invalidated live object crash DiffKit while diffing
  kDrive/UI/Controller/Files/Upload/UploadQueueViewController.swift
  kDrive/UI/View/Files/Upload/UploadTableViewCell.swift
Labels: bug

#1400 fix(PhotoSyncSettingsViewController): Realm crash on wrong thread on save settings
  kDrive/UI/Controller/Menu/PhotoSyncSettingsViewController.swift
  kDriveCore/Data/UploadQueue/Servicies/PhotoLibraryUploader+Sync.swift
Labels: bug

#1417 fix: Display formatted folder name in upload folders view
  kDrive/UI/View/Files/Upload/UploadFolderTableViewCell.swift
Labels: bug

#1416 chore(Localizable.strings): Ran script to update all
  kDrive/Resources/de.lproj/Localizable.strings
  kDrive/Resources/en.lproj/Localizable.strings
  kDrive/Resources/es.lproj/Localizable.strings
  kDrive/Resources/fr.lproj/Localizable.strings
  kDrive/Resources/it.lproj/Localizable.strings
Labels: drive_quota
