Repository Infomaniak/ios-kDrive, pull requests merged in 2025-03, with the labels that each got.

#1465 feat: Public share single file
  kDrive/AppRouter.swift
  kDrive/UI/Controller/Menu/Share/PublicShareSingleFileViewModel.swift
  kDrive/UI/Controller/Menu/Share/PublicShareViewModel.swift
  kDriveCore/Utils/AppNavigable.swift
  kDriveCore/Utils/Deeplinks/UniversalLinksHelper.swift
  kDriveCore/Utils/InExtensionRouter.swift
  kDriveTestShared/MCKRouter.swift
Labels: public_share

#1473 fix(MultipleSelectionFloatingPanelViewController+Actions): Broken DI
  kDrive/UI/Controller/Files/MultipleSelectionFloatingPanelViewController+Actions.swift
  kDriveCore/Data/DownloadQueue/DownloadQueueable.swift
Labels: bug

#1477 feat: Add if let to safe the value
  kDrive/UI/Controller/Menu/PhotoList/PhotoListViewController.swift
Labels: bug

#1485 fix: Incorrect cell count
  kDrive/UI/Controller/Menu/ParameterTableViewController.swift
Labels: bug

#1484 fix(FileProviderExtension): Resolve correct DI type
  kDriveFileProvider/FileProviderExtension.swift
Labels: bug

#1486 chore: Release build 5.3.1-b2
  TestFlight/WhatToTest.en-GB.txt
  TestFlight/WhatToTest.fr-FR.txt
Labels: release

#1479 fix: Crash on force unwrap
  kDrive/UI/Controller/Files/Save File/SelectFolderViewController.swift
Labels: bug

#1471 feat: PhotoSync is performed on a dedicated UploadQueue
  kDrive/AppRouter.swift
  kDrive/UI/Controller/Menu/PhotoSyncSettingsViewController.swift
  kDriveCore/DI/FactoryService.swift
  kDriveCore/Data/Models/Upload/UploadFile.swift
  kDriveCore/Data/Upload/Servicies/UploadService/Parallelism/UploadParallelismOrchestrator.swift
  kDriveCore/Data/Upload/Servicies/UploadService/Parallelism/WorkloadParallelismHeuristic.swift
  kDriveCore/Data/Upload/Servicies/UploadService/UploadService+Notifications.swift
  kDriveCore/Data/Upload/Servicies/UploadService/UploadService+Observation.swift
  kDriveCore/Data/Upload/Servicies/UploadService/UploadService+Publish.swift
  kDriveCore/Data/Upload/Servicies/UploadService/UploadService.swift
  kDriveCore/Data/Upload/Servicies/UploadService/UploadServiceable.swift
  kDriveCore/Data/Upload/UploadQueue/Queue/UploadQueue+Queue.swift
  kDriveCore/Data/Upload/UploadQueue/Queue/UploadQueue.swift
  kDriveCore/Data/Upload/UploadQueue/Queue/UploadQueueObserver.swift
  kDriveCore/Data/Upload/UploadQueue/Queue/UploadQueueable.swift
  kDriveCore/Services/BackgroundTasksService.swift
Labels: refactor

#1487 fix(FilePresenter): Function presentParent works again
  kDrive/UI/Controller/Files/FilePresenter.swift
Labels: bug

#1489 fix: Text preview of large or corrupted files crashes
  kDrive/UI/View/Files/Preview/CodePreviewCollectionViewCell.swift
Labels: bug
