Repository Infomaniak/ios-kDrive, pull requests merged in 2025-07, with the labels that each got.

#1599 fix: Remove background of the button in dark mode
  kDrive/UI/View/Home/InsufficientStorageCollectionViewCell.xib
Labels: bug

#1598 fix: Prevent presentation issues on iPad
  kDrive/UI/Controller/Files/Preview/PreviewViewController.swift
  kDrive/UI/Controller/Files/SidebarViewController.swift
Labels: bug

#1594 feat: Preview deeplink without having the file in realm db
  kDrive/AppRouter+SharedWithMe.swift
  kDrive/AppRouter.swift
  kDrive/Resources/de.lproj/Localizable.strings
  kDrive/Resources/en.lproj/Localizable.strings
  kDrive/Resources/es.lproj/Localizable.strings
  kDrive/Resources/fr.lproj/Localizable.strings
  kDrive/Resources/it.lproj/Localizable.strings
  kDrive/UI/Controller/Files/File List/FileListViewController.swift
  kDriveCore/Data/Cache/AccountManager.swift
  kDriveCore/Data/Cache/DriveFileManager/DriveFileManager+SharedWithMe.swift
  kDriveCore/Utils/Deeplinks/SharedWithMeLink.swift
  kDriveCore/Utils/Deeplinks/SharedWithMeService.swift
  kDriveCore/Utils/Routable.swift
  kDriveTests/UTNavigationManager.swift
  kDriveTests/kDriveCore/DeepLinks/UTSharedWithMeLink.swift
Labels: feature, deeplink

#1604 chore: Release build 5.7.0-b29
  TestFlight/WhatToTest.en-GB.txt
  TestFlight/WhatToTest.fr-FR.txt
  Tuist/Package.resolved
Labels: release

#1593 fix: Limit errors notifications when upload
  kDriveCore/Data/Upload/Servicies/UploadService/UploadService+Notifications.swift
  kDriveCore/Data/Upload/Servicies/UploadService/UploadService.swift
  kDriveCore/Utils/NotificationsHelper.swift
Labels: optimization

#1609 fix: Crash activity on realm invalidated object
  kDrive/UI/Controller/Home/HomeRecentActivitiesController.swift
  kDriveCore/Data/Cache/DriveFileManager/DriveFileManager+Query.swift
Labels: bug

#1613 chore: Release build 5.8.0-b37
  TestFlight/WhatToTest.en-GB.txt
  TestFlight/WhatToTest.fr-FR.txt
Labels: release

#1616 chore: Bump Tuist to 55.0 to match Mail setup
  .mise.toml
Labels: chore

#1608 feat: Add trash deeplinks
  kDrive/AppRouter+SharedWithMe.swift
  kDrive/AppRouter+Trash.swift
  kDrive/AppRouter.swift
  kDrive/UI/Controller/LoginDelegateHandler.swift
  kDriveCore/DI/FactoryService.swift
  kDriveCore/Data/Cache/AccountManager.swift
  kDriveCore/Data/Cache/DriveFileManager/DriveFileManager.swift
  kDriveCore/Utils/DeeplinkParser.swift
  kDriveCore/Utils/Deeplinks/DeeplinkService.swift
  kDriveCore/Utils/Deeplinks/SharedWithMeService.swift
  kDriveCore/Utils/Deeplinks/TrashLink.swift
  kDriveCore/Utils/Routable.swift
  kDriveTests/kDrive/Launch/MockAccountManager.swift
  kDriveTests/kDriveCore/DeepLinks/UTTrashLink.swift
Labels: deeplink

#1601 feat: Interapp login
  Project.swift
  Tuist/Package.resolved
  Tuist/Package.swift
  kDrive/AppDelegate.swift
  kDrive/Resources/kDrive.entitlements
  kDrive/UI/Controller/LoginDelegateHandler.swift
  kDrive/UI/Controller/WaveViewController.swift
  kDriveCore/DI/FactoryService.swift
Labels: feature

#1619 chore: Release build 5.8.0-b41
  TestFlight/WhatToTest.en-GB.txt
  TestFlight/WhatToTest.fr-FR.txt
  Tuist/Package.resolved
Labels: release

#1623 chore: Release build 5.8.1
  TestFlight/WhatToTest.en-GB.txt
  TestFlight/WhatToTest.fr-FR.txt
  Tuist/Package.resolved
  Tuist/ProjectDescriptionHelpers/Constants.swift
Labels: release
