Repository Infomaniak/ios-kDrive, pull requests merged in 2025-09, with the labels that each got.

#1660 feat: Support for kSuite pro part 2
  kDrive/UI/Controller/Files/FileActionsFloatingPanelViewController+Actions.swift
  kDrive/UI/Controller/Files/MultipleSelectionFloatingPanelViewController.swift
  kDrive/UI/Controller/Files/Rights and Share/RightsSelectionViewController.swift
  kDrive/UI/Controller/Files/Rights and Share/ShareLinkSettingsViewController.swift
  kDrive/UI/Controller/Home/HomeViewController.swift
  kDrive/UI/Controller/Menu/MenuViewController.swift
  kDrive/UI/View/Files/FileDetail/ShareLink/RightsSelectionTableViewCell.swift
  kDrive/UI/View/Files/FileDetail/ShareLink/RightsSelectionTableViewCell.xib
  kDrive/UI/View/Files/FileDetail/ShareLink/ShareLinkSettingTableViewCell.swift
  kDrive/UI/View/Files/FileDetail/ShareLink/ShareLinkSettingTableViewCell.xib
  kDrive/UI/View/Home/InsufficientStorageCollectionViewCell.swift
  kDrive/UI/View/Home/InsufficientStorageCollectionViewCell.xib
  kDrive/Utils/FileActionsHelper.swift
  kDrive/Utils/KSuitePro/KSuiteGetProViewController.swift
  kDrive/Utils/KSuitePro/KSuiteUpsaleViewController.swift
  kDriveCore/Data/Models/Drive/Drive+Quota.swift
  kDriveCore/UI/UIConstants.swift
  kDriveCore/Utils/String+Extension.swift
Labels: feature, kSuite Pro

#1676 chore: Release build 5.9.0-b52
  TestFlight/WhatToTest.en-GB.txt
  TestFlight/WhatToTest.fr-FR.txt
  Tuist/Package.resolved
  Tuist/ProjectDescriptionHelpers/Constants.swift
Labels: release

#1677 feat(iOS 26): App Icons
  Project.swift
  kDrive/Resources/AppIcon.icon/Assets/1 – Layer.svg
  kDrive/Resources/AppIcon.icon/Assets/2 – Layer.svg
  kDrive/Resources/AppIcon.icon/Assets/3 – Layer.svg
  kDrive/Resources/AppIcon.icon/Assets/4 – Layer.svg
  kDrive/Resources/AppIcon.icon/icon.json
  kDrive/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  kDrive/Resources/Assets.xcassets/AppIcon.appiconset/kDrive-Dark.png
  kDrive/Resources/Assets.xcassets/AppIcon.appiconset/kDrive-Light.png
  kDrive/Resources/Assets.xcassets/AppIcon.appiconset/kDrive-Tinted.png
  kDrive/Resources/Info.plist
Labels: iOS26

#1688 chore: Release build 5.10.0-b55
  TestFlight/WhatToTest.en-GB.txt
  TestFlight/WhatToTest.fr-FR.txt
Labels: release, iOS26

#1693 feat: Send a local notification to delete uploaded photos
  kDrive/AppRouter.swift
  kDrive/Resources/de.lproj/Localizable.strings
  kDrive/Resources/en.lproj/Localizable.strings
  kDrive/Resources/es.lproj/Localizable.strings
  kDrive/Resources/fr.lproj/Localizable.strings
  kDrive/Resources/it.lproj/Localizable.strings
  kDriveCore/Services/BackgroundTasksService.swift
  kDriveCore/Utils/AppNavigable.swift
  kDriveCore/Utils/InExtensionRouter.swift
  kDriveCore/Utils/NotificationsHelper.swift
  kDriveTestShared/MCKRouter.swift
Labels: feature, optimization

#1691 fix: Share link quota
  kDrive/UI/Controller/Files/Rights and Share/KSuiteRestrictions.swift
  kDrive/UI/Controller/Files/Rights and Share/RightsSelectionViewController.swift
  kDrive/UI/Controller/Files/Rights and Share/ShareAndRightsViewController.swift
  kDrive/UI/Controller/NewFolder/NewFolderTypeTableViewController.swift
  kDrive/UI/View/Files/FileDetail/ShareLink/ShareLinkTableViewCell.swift
  kDriveCore/Data/Models/Drive/Drive+Quota.swift
Labels: enhancement

#1700 chore: Release build 5.10.2-b56
  TestFlight/WhatToTest.en-GB.txt
  TestFlight/WhatToTest.fr-FR.txt
  Tuist/ProjectDescriptionHelpers/Constants.swift
Labels: release

#1701 fix: Only migrate on initial launch
  kDrive/SceneDelegate.swift
Labels: bug

#1702 chore: Release build 5.10.2-b59
  TestFlight/WhatToTest.en-GB.txt
  TestFlight/WhatToTest.fr-FR.txt
Labels: release
