Repository Infomaniak/ios-kDrive, pull requests merged in 2025-05, with the labels that each got.

#1520 fix: Correct empty view display logic
  kDrive/UI/Controller/Files/File List/FileListViewModel.swift
Labels: bug

#1508 feat: Add possibility to select all files in offline root
  kDrive/UI/Controller/Files/File List/FileListViewController.swift
  kDrive/UI/Controller/Files/File List/MultipleSelectionFileListViewModel.swift
  kDrive/UI/Controller/Files/MultipleSelectionFloatingPanelViewController+Actions.swift
  kDrive/UI/Controller/Files/MultipleSelectionFloatingPanelViewController.swift
  kDrive/UI/Controller/Menu/OfflineFilesViewModel.swift
  kDrive/Utils/FileActionsHelper.swift
  kDriveCore/Utils/Constants.swift
Labels: feature

#1521 fix(PhotoSyncSettingsViewController): Destination folder trashed was soft locking
  kDrive/UI/Controller/Menu/PhotoSyncSettingsViewController.swift
Labels: bug

#1516 fix: Scaling issues
  kDrive/UI/Controller/Files/ColorSelectionFloatingPanelViewController.swift
  kDrive/UI/Controller/Files/File List/MultipleSelectionFileListViewModel.swift
  kDrive/UI/Controller/Files/MultipleSelectionFloatingPanelViewController.swift
  kDrive/UI/Controller/Menu/SwitchUserViewController.swift
  kDrive/UI/Controller/Menu/Trash/TrashListViewModel.swift
  kDrive/Utils/FileActionsHelper.swift
  kDriveCore/Utils/Constants.swift
Labels: bug

#1528 fix: Correctly set isWifiOnly default value in user defaults on clean install
  kDrive/UI/Controller/Menu/PhotoSyncSettingsViewController.swift
Labels: bug

#1502 feat: Show all folders while downloading a file
  Tuist/ProjectDescriptionHelpers/ExtensionTarget.swift
  kDrive/AppRestorationService.swift
  kDrive/AppRouter.swift
  kDrive/Resources/de.lproj/Localizable.strings
  kDrive/Resources/en.lproj/Localizable.strings
  kDrive/Resources/es.lproj/Localizable.strings
  kDrive/Resources/fr.lproj/Localizable.strings
  kDrive/Resources/it.lproj/Localizable.strings
  kDrive/UI/Controller/Files/File List/ConcreteFileListViewModel.swift
  kDrive/UI/Controller/Files/File List/FileListViewController.swift
  kDrive/UI/Controller/Files/FilePresenter.swift
  kDrive/UI/Controller/Files/RootMenuViewController.swift
  kDrive/UI/Controller/Files/Save File/LocationFolderViewController.swift
  kDrive/UI/Controller/Files/Save File/SaveFileViewController+SelectDriveDelegate.swift
  kDrive/UI/Controller/Files/Save File/SelectFolderViewController.swift
  kDrive/UI/Controller/Home/HomeLargeTitleHeaderView.swift
  kDrive/UI/Controller/Home/HomeViewController.swift
  kDrive/UI/Controller/Home/RootMenuHeaderView.swift
  kDrive/UI/Controller/MainTabViewController.swift
  kDrive/UI/Controller/Menu/PhotoList/PhotoListViewController.swift
  kDrive/UI/View/Menu/PhotoList/ReusableHeaderView.swift
  kDrive/UI/View/Menu/PhotoList/ReusableHeaderView.xib
  kDrive/UI/View/Menu/RootMenuCell.swift
  kDriveCore/Services/AppContextService.swift
  kDriveCore/Services/AppRestorationServiceable.swift
  kDriveCore/UI/UIConstants.swift
  kDriveCore/Utils/AppNavigable.swift
  kDriveCore/Utils/InExtensionRouter.swift
  kDriveTestShared/MCKRouter.swift
  kDriveTests/StateRestoration/UTSceneRestorationMetadata.swift
Labels: feature

#1531 chore: Release build 5.5.0-b2
  TestFlight/WhatToTest.en-GB.txt
  TestFlight/WhatToTest.fr-FR.txt
Labels: release

#1533 chore: Update App Icon
  kDrive/Resources/Assets.xcassets/AppIcon.appiconset/kDrive-Dark.png
  kDrive/Resources/Assets.xcassets/AppIcon.appiconset/kDrive-Light.png
  kDrive/Resources/Assets.xcassets/AppIcon.appiconset/kDrive-Tinted.png
Labels: enhancement

#1532 fix: Crash in upload queue view controller
  kDrive/UI/Controller/Files/Upload/UploadQueueViewController.swift
  kDrive/UI/View/Files/Upload/UploadTableViewCell.swift
  kDriveCore/Data/Cache/PhotoSyncSettings.swift
  kDriveCore/Data/Upload/Servicies/PhotoLibraryUploader/PhotoLibraryUploader+Sync.swift
  kDriveCore/Data/Upload/Servicies/PhotoLibraryUploader/PhotoLibraryUploader.swift
Labels: bug

#1525 fix: Empty photo sync upload queue on disable photo sync
  kDriveCore/Data/Upload/Servicies/PhotoLibraryUploader/PhotoLibraryUploader+Sync.swift
  kDriveCore/Data/Upload/Servicies/PhotoLibraryUploader/PhotoLibraryUploader.swift
  kDriveCore/Data/Upload/Servicies/UploadService/UploadService+Datasource.swift
  kDriveCore/Data/Upload/Servicies/UploadService/UploadService.swift
  kDriveCore/Data/Upload/Servicies/UploadService/UploadServiceable.swift
Labels: bug

#1538 fix: Make sure a DB transaction is finished before we notify a change
  kDriveCore/Data/Cache/DriveFileManager/DriveFileManager.swift
Labels: bug

#1540 fix: Correctly setup observation in order to prevent a performance issue
  kDrive/UI/Controller/Files/Preview/PreviewViewController.swift
Labels: bug

#1544 refactor: Change error message
  kDrive/Resources/de.lproj/Localizable.strings
  kDrive/Resources/en.lproj/Localizable.strings
  kDrive/Resources/es.lproj/Localizable.strings
  kDrive/Resources/fr.lproj/Localizable.strings
  kDrive/Resources/it.lproj/Localizable.strings
  kDriveCore/Data/Models/DriveError.swift
Labels: bug

#1547 chore: Release build 5.5.0-b4
  TestFlight/WhatToTest.en-GB.txt
  TestFlight/WhatToTest.fr-FR.txt
  Tuist/Package.resolved
Labels: release

#1523 refactor: Removed photo scan batching
  kDrive/UI/Controller/Files/File List/FileListViewController.swift
  kDrive/UI/Controller/Files/Upload/UploadQueueViewController.swift
  kDriveCore/Data/Upload/Servicies/PhotoLibraryUploader/PhotoLibraryUploader+Scan.swift
Labels: bug, enhancement

#1545 chore: Upgrade lottie version to 4.4.3
  Tuist/Package.resolved
  Tuist/Package.swift
  kDrive/UI/Controller/Floating Panel Information/DropBoxFloatingPanelViewController.swift
  kDrive/UI/Controller/Floating Panel Information/FolderColorFloatingPanelViewController.swift
  kDrive/UI/Controller/Floating Panel Information/InformationFloatingPanel.storyboard
  kDrive/UI/Controller/Floating Panel Information/InformationFloatingPanelViewController.swift
  kDrive/UI/Controller/Floating Panel Information/SavePhotosFloatingPanelViewController.swift
  kDrive/UI/Controller/Floating Panel Information/SecureLinkFloatingPanelViewController.swift
  kDrive/UI/View/Onboarding/SlideCollectionViewCell.swift
  kDrive/UI/View/Onboarding/SlideCollectionViewCell.xib
Labels: enhancement

#1541 feat: Add bug report
  Project.swift
  Tuist/Package.resolved
  Tuist/Package.swift
  kDrive/Resources/de.lproj/Localizable.strings
  kDrive/Resources/en.lproj/Localizable.strings
  kDrive/Resources/es.lproj/Localizable.strings
  kDrive/Resources/fr.lproj/Localizable.strings
  kDrive/Resources/it.lproj/Localizable.strings
  kDrive/UI/Controller/MainTabViewController.swift
  kDrive/UI/Controller/Menu/ParameterTableViewController.swift
  kDriveCore/DI/FactoryService.swift
  kDriveCore/Data/Cache/AccountManager.swift
Labels: feature

#1548 fix: Limit fetch querry to first one
  kDriveCore/Data/Models/Upload/UploadFile.swift
Labels: optimization

#1554 chore: Release build 5.6.0-b1
  TestFlight/WhatToTest.en-GB.txt
  TestFlight/WhatToTest.fr-FR.txt
  Tuist/Package.resolved
  Tuist/ProjectDescriptionHelpers/Constants.swift
Labels: release
